#Proje ana ekran tasarımı
print("╔════════════════════════╗")
print("║      VEKTOREL APP      ║")
print("╠════════════════════════╣")
print("║   1-Oyunlar            ║")
print("║   2-Çizimler           ║")
print("║   3-Hesaplamalar       ║")
print("║   4-                   ║")
print("║   5-                   ║")
print("║   6-                   ║")
print("║   7-                   ║")
print("║    Seçiminiz?          ║")
print("╚════════════════════════╝")
# secim = input("Seçiminiz nedir?")
# secim = int(input())
secim = input()
print(f"Seçimin {secim} idi.")
print(f"Girdiğin {secim} verisi {type(secim)} türünde.")